version: "3.9"
services:
  app:
    container_name: app_container
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    container_name: db_container
    image: arm64v8/postgres:16.1-alpine
    volumes:
      - template-vol:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: template
volumes:
  template-vol: