version: "3.9"
services:
  app:
    container_name: app_container
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    container_name: db_container
    build:
      context: ./db
      args:
        - SAMPLE_DATA=${SAMPLE_DATA}
    tty: true
    volumes:
      - template-vol:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      SAMPLE_DATA: ${SAMPLE_DATA}
volumes:
  template-vol: